apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.secret.adminUser | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | b64enc }}
  KC_DB_URL: {{ .Values.secret.dbUrl | b64enc }}
  KC_DB_USERNAME: {{ .Values.secret.dbUsername | b64enc }}
  KC_DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}
