apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env
  namespace: keycloak
data:
  KC_HOSTNAME: "keycloak-staging.example.com"   # TODO: เปลี่ยนเป็น hostname จริง
  KC_HOSTNAME_STRICT: "false"
